# Generated by Django 2.1.7 on 2019-03-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='id',
        ),
        migrations.AddField(
            model_name='history',
            name='main_id',
            field=models.AutoField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='history',
            name='u_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
