# Generated by Django 2.1.7 on 2019-03-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20190317_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='u_id',
            field=models.CharField(default=0, max_length=30, null=True),
        ),
    ]
